force-app/logger/sfdc-logger/objects/Logger_Config__c/fields/Is_Info_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Info_Enabled__c</fullName>
    <description>Identifies if the Logs of Severety Info should be created</description>
    <defaultValue>false</defaultValue>
    <label>Is Info Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/logger/sfdc-logger/objects/Logger_Config__c/fields/Is_Logger_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Logger_Enabled__c</fullName>
    <description>Identifies of Logger is enabled</description>
    <defaultValue>false</defaultValue>
    <label>Is Logger Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LoggerService.cls
public without sharing class LoggerService {
    private Logger_Config__c loggerSettings;

    public LoggerService() {
        loggerSettings = Logger_Config__c.getOrgDefaults();
    }

    public Logger_Config__c getConfig() {
        return loggerSettings;
    }

    public void updateLoggerService(Boolean enabled) {
        loggerSettings.Is_Debug_Enabled__c = enabled;
        loggerSettings.Is_Error_Enabled__c = enabled;
        loggerSettings.Is_Info_Enabled__c = enabled;
        loggerSettings.Is_Logger_Enabled__c = enabled;
        loggerSettings.Is_Success_Enabled__c = enabled;

        upsert as system loggerSettings;
    }

    public Boolean isLoggingEnabled() {
        return loggerSettings.Is_Logger_Enabled__c;
    }
}