force-app/main/default/objects/UTXO_Address__c/UTXO_Address__c.object-meta.xml
<CustomObject>
    <label>UTXO Address</label>
    <nameField>
        <displayFormat>UTXO-{0000}</displayFormat>
        <label>UTXO Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UTXO Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UTXO_Address__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UTXO_Address__c/fields/Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Private_Key__c</fullName>
    <label>Private Key</label>
    <type>LongTextArea</type>
    <length>32768</length>
</CustomField> 

force-app/main/default/objects/UTXO_Address__c/fields/Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Public_Key__c</fullName>
    <label>Public Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UTXO_Address__c/fields/Staking_Key_Hash__c.field-meta.xml
<CustomField>
    <fullName>Staking_Key_Hash__c</fullName>
    <label>Staking Key Hash</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UTXO_Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Receiving</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Change</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UTXO_Address__c/fields/Wallet__c.field-meta.xml
<CustomField>
    <fullName>Wallet__c</fullName>
    <label>Wallet</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>UTXO Addresses</relationshipLabel>
    <relationshipName>UTXO_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wallet__c/fields/Wallet_Set__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Set__c</fullName>
    <label>Wallet Set</label>
    <referenceTo>Wallet_Set__c</referenceTo>
    <relationshipLabel>Wallets</relationshipLabel>
    <relationshipName>Wallets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wallet_Set__c/Wallet_Set__c.object-meta.xml
<CustomObject>
    <label>Wallet Set</label>
    <nameField>
        <displayFormat>WS-{0000}</displayFormat>
        <label>Wallet Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wallet Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wallet_Set__c/fields/Seed_Phrase__c.field-meta.xml
<CustomField>
    <fullName>Seed_Phrase__c</fullName>
    <description>The Seed Phrase to Generate Wallets</description>
    <label>Seed Phrase</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Wallet_Set__c/fields/Wallet_Name__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Name__c</fullName>
    <label>Wallet Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WalletCtrlTest.cls
@isTest
private class WalletCtrlTest {
    private static final String ASSERT_MESSAGE_WALLET_ID = 'Wallet ID should match';
    private static final String ASSERT_MESSAGE_ADDRESS = 'Address should match';
    private static final String ASSERT_MESSAGE_TYPE = 'Type should match';
    private static final String ASSERT_MESSAGE_BALANCE = 'Balance should match';
    private static final String TEST_PRIVATE_KEY = '0123456789abcdef0123456789abcdef';
    private static final String TEST_SEED_PHRASE = 'test seed phrase';
    private static final String TEST_ADDRESS = 'testAddress123';
    private static final Decimal TEST_BALANCE = 1000000;
    
    @testSetup
    private static void testData() {
        AdaWalletsService.setPrivateKey(TEST_PRIVATE_KEY);

        Wallet_Set__c walletSet = new Wallet_Set__c(
            Wallet_Name__c = 'Test Wallet',
            Seed_Phrase__c = DataEncryptor.encrypt(TEST_SEED_PHRASE)
        );
        insert walletSet;
        
        Wallet__c wallet = new Wallet__c(
            Name = 'Test Wallet',
            Wallet_Set__c = walletSet.Id
        );
        insert wallet;
        
        UTXO_Address__c utxoAddress = new UTXO_Address__c(
            Wallet__c = wallet.Id,
            Address__c = TEST_ADDRESS,
            Index__c = 0,
            Public_Key__c = 'testPublicKey',
            Staking_Key_Hash__c = 'testStakingKeyHash',
            Path__c = 'testPath',
            Private_Key__c = 'testPrivateKey',
            Type__c = '0'
        );
        insert utxoAddress;
    }

    private class BlockfrostServiceMock implements HttpCalloutMock {
        private Decimal txCount;
        
        public BlockfrostServiceMock(Decimal txCount) {
            this.txCount = txCount;
        }
        
        public HTTPResponse respond(HTTPRequest request) {
            HTTPResponse response = new HTTPResponse();
            response.setStatusCode(200);
                
            response.setBody('{"tx_count": ' + txCount + ',"received_sum": [{"unit": "lovelace", "quantity": "' + TEST_BALANCE + '"}], "sent_sum": [{"unit": "lovelace", "quantity": "0"}]}');                        
            return response;
        }
    }
} 