force-app/main/default/objects/UTXO_Address__c/UTXO_Address__c.object-meta.xml
<CustomObject>
    <label>UTXO Address</label>
    <nameField>
        <displayFormat>UTXO-{0000}</displayFormat>
        <label>UTXO Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UTXO Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UTXO_Address__c/fields/Wallet__c.field-meta.xml
<CustomField>
    <fullName>Wallet__c</fullName>
    <label>Wallet</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>UTXO Addresses</relationshipLabel>
    <relationshipName>UTXO_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/UTXOAssetSyncQueueable.cls
public class UTXOAssetSyncQueueable implements Queueable, Database.AllowsCallouts {
    private List<Id> utxoAddressIds;
    
    public UTXOAssetSyncQueueable(List<Id> utxoAddressIds) {
        this.utxoAddressIds = utxoAddressIds;
    }
    
    public void execute(QueueableContext context) {
        Set<Id> processedWalletIds = new Set<Id>();
        
        for (Id utxoAddressId : utxoAddressIds) {
            Map<String, Object> result = UTXOAssetController.syncAssetsAndTransactions(utxoAddressId);            
            
            UTXO_Address__c utxoAddress = [SELECT Wallet__c FROM UTXO_Address__c WHERE Id = :utxoAddressId LIMIT 1];
            processedWalletIds.add(utxoAddress.Wallet__c);
        }
        
        // Publish wallet sync event for each unique wallet after all syncs are complete
        for (Id walletId : processedWalletIds) {
            BlockfrostService.publishWalletSyncEvent(walletId, 'assetsUpdated');
        }
    }
} 