force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wallet__c/fields/Account_Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Account_Private_Key__c</fullName>
    <label>Account Private Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wallet__c/fields/Account_Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Account_Public_Key__c</fullName>
    <label>Account Public Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wallet__c/fields/Wallet_Set__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Set__c</fullName>
    <label>Wallet Set</label>
    <referenceTo>Wallet_Set__c</referenceTo>
    <relationshipLabel>Wallets</relationshipLabel>
    <relationshipName>Wallets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wallet_Set__c/Wallet_Set__c.object-meta.xml
<CustomObject>
    <label>Wallet Set</label>
    <nameField>
        <displayFormat>WS-{0000}</displayFormat>
        <label>Wallet Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wallet Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wallet_Set__c/fields/Root_Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Root_Private_Key__c</fullName>
    <label>Root Private Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wallet_Set__c/fields/Root_Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Root_Public_Key__c</fullName>
    <label>Root Public Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wallet_Set__c/fields/Seed_Phrase__c.field-meta.xml
<CustomField>
    <fullName>Seed_Phrase__c</fullName>
    <description>The Seed Phrase to Generate Wallets</description>
    <label>Seed Phrase</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Wallet_Set__c/fields/Wallet_Name__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Name__c</fullName>
    <label>Wallet Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WalletSetCtrl.cls
public with sharing class WalletSetCtrl {
    @AuraEnabled
    public static Id createWalletSet(String walletName, String seedPhrase, String rootPrivateKey, String rootPublicKey) {
        try {
            Wallet_Set__c walletSet = new Wallet_Set__c();
            walletSet.Wallet_Name__c = walletName;
            walletSet.Seed_Phrase__c = DataEncryptor.encrypt(seedPhrase);
            walletSet.Root_Private_Key__c = DataEncryptor.encrypt(rootPrivateKey);
            walletSet.Root_Public_Key__c = rootPublicKey;
            insert walletSet;
            Logger.logInfo('Wallet Set was created by ' + UserInfo.getName() + ' (Id: ' + UserInfo.getUserId() + ') with ID: ' + walletSet.Id);
            return walletSet.Id;
        } catch (Exception e) {
            throw new AuraHandledException('Error creating Wallet Set: ' + e.getMessage());
        } finally {
            Logger.commitLogs();
        }
    }

    @AuraEnabled(cacheable=true)
    public static Wallet_Set__c getWalletSetDetails(String walletRecordId) {
        try {
            Wallet__c wallet = WalletSelector.getWalletById(walletRecordId);
            if (wallet.Wallet_Set__c == null) {
                throw new AuraHandledException('No Wallet_Set__c record associated with this Wallet__c record.');
            }
            return WalletSetSelector.getWalletSetById(wallet.Wallet_Set__c);
        } catch (Exception e) {
            throw new AuraHandledException('Error fetching Wallet_Set__c details: ' + e.getMessage());
        }
    }

    @AuraEnabled
    public static void updateWallet(String walletId, String accountPublicKey, String accountPrivateKey) {
        try {
            Wallet__c wallet = WalletSelector.getWalletById(walletId);
            wallet.Account_Public_Key__c = accountPublicKey;
            wallet.Account_Private_Key__c = accountPrivateKey;
            update wallet;
        } catch (Exception e) {
            throw new AuraHandledException('Error updating Wallet__c record: ' + e.getMessage());
        }
    }
}