force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wallet__c/fields/Account_Index__c.field-meta.xml
<CustomField>
    <fullName>Account_Index__c</fullName>
    <label>Account Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Wallet__c/fields/Account_Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Account_Private_Key__c</fullName>
    <label>Account Private Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wallet__c/fields/Account_Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Account_Public_Key__c</fullName>
    <label>Account Public Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wallet__c/fields/Wallet_Set__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Set__c</fullName>
    <label>Wallet Set</label>
    <referenceTo>Wallet_Set__c</referenceTo>
    <relationshipLabel>Wallets</relationshipLabel>
    <relationshipName>Wallets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wallet_Set__c/Wallet_Set__c.object-meta.xml
<CustomObject>
    <label>Wallet Set</label>
    <nameField>
        <displayFormat>WS-{0000}</displayFormat>
        <label>Wallet Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wallet Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/WalletSelector.cls
public with sharing class WalletSelector {
    public static Wallet__c getWalletById(Id walletId) {
        return [SELECT Id, Wallet_Set__c, Account_Private_Key__c, Account_Public_Key__c, Account_Index__c FROM Wallet__c WHERE Id = :walletId WITH SECURITY_ENFORCED LIMIT 1];
    }
    
    public static List<Wallet__c> getWalletByWalletSetAndAccountIndex(String walletSetId, Integer accountIndex) {
        return [SELECT Id FROM Wallet__c WHERE Wallet_Set__c = :walletSetId AND Account_Index__c = :accountIndex LIMIT 1];
    }

    public static List<Wallet__c> getWalletsExcludingIds(Set<Id> walletIds) {
        return [SELECT Wallet_Set__c, Account_Index__c
            FROM Wallet__c
            WHERE Wallet_Set__c != null AND Account_Index__c != null
            AND Id NOT IN :walletIds
            WITH SECURITY_ENFORCED];
    }
}