force-app/AqLib/apex/core/main/objects/LogDgt__c/LogDgt__c.object-meta.xml
<CustomObject>
    <description>Event logging object.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Unique programmatic identifier for the event, use for filtering, workflows, etc.</description>
    <inlineHelpText>Unique programmatic identifier for the event, use for filtering, workflows, etc.</inlineHelpText>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/Detail__c.field-meta.xml
<CustomField>
    <fullName>Detail__c</fullName>
    <description>Detail such as stack trace, should be in JSON format whenever possible.</description>
    <inlineHelpText>Detail such as stack trace, should be in JSON format whenever possible.</inlineHelpText>
    <label>Detail</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Specifies whether the event is directed to the end user, indicates a business rule violation, or indicates an internal error. Used to determine the amount of detail shown to the end user.</description>
    <inlineHelpText>Specifies whether the event is directed to the end user, indicates a business rule violation, or indicates an internal error. Used to determine the amount of detail shown to the end user.</inlineHelpText>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/LogDate__c.field-meta.xml
<CustomField>
    <fullName>LogDate__c</fullName>
    <defaultValue>Now()</defaultValue>
    <description>Date and time of the event.</description>
    <inlineHelpText>Date and time of the event.</inlineHelpText>
    <label>Log Date</label>
    <type>DateTime</type>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The main text message associated with the event.</description>
    <inlineHelpText>The main text message associated with the event.</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/ResultType__c.field-meta.xml
<CustomField>
    <fullName>ResultType__c</fullName>
    <description>When the event indicates successful result of an operation, this indicates the data type of the result.</description>
    <inlineHelpText>When the event indicates successful result of an operation, this indicates the data type of the result.</inlineHelpText>
    <label>Result Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>Use to indicate the area that the event refers to, such as the related field or fields or the JSON path.</description>
    <inlineHelpText>Use to indicate the area that the event refers to, such as the related field or fields or the JSON path.</inlineHelpText>
    <label>Scope</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/ScopeType__c.field-meta.xml
<CustomField>
    <fullName>ScopeType__c</fullName>
    <description>The type of object that the scope refers to.</description>
    <inlineHelpText>The type of object that the scope refers to.</inlineHelpText>
    <label>Scope Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>Indicates whether the event represents an error, warning, or is informational.</description>
    <inlineHelpText>Indicates whether the event represents an error, warning, or is informational.</inlineHelpText>
    <label>Severity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>PartialError</fullName>
                <label>Partial Error</label>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>RolledBack</fullName>
                <label>Rolled Back</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Indicates the class, function, page, or other component where the event originated.</description>
    <inlineHelpText>Indicates the class, function, page, or other component where the event originated.</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/AqLib/apex/core/main/apex/classes/AqLog.cls
/*
 * Copyright (c) 2022, Aquiva Labs LLC. All rights reserved.
 * 
 * 
 * Redistribution and use in source and binary forms, with or without modification, 
 *   are permitted provided that the following conditions are met:
 * 
 * - Redistributions of source code must retain the above copyright notice, 
 *     this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice, 
 *     this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 * - Neither the name of the Aquiva Labs LLC nor the names of its contributors
 *     may be used to endorse or promote products derived from this software without
 *     specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
 *  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL 
 *  THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 *  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**/

/**
 * @description Event logger. [LogDgt__c](https://bitbucket.org/aquiva/aqlib/src/develop/AqLib/core/main/objects/LogDgt__c/) custom object is used.
 * @group apex/core
 */
public inherited sharing class AqLog {

    private static SObjectType LOG_SOBJECT_TYPE = LogDgt__c.getSObjectType();
    private static List<String> LOG_FIELDS = new List<String> {
        'Id', 'LogDate__c', 'Level__c', 'Severity__c', 'Code__c', 'Source__c',
        'ResultType__c', 'ScopeType__c', 'Scope__c', 'Message__c', 'Detail__c'
    };

    public static LogDgt__c generateLogRecord(AqResult result) {
        LogDgt__c log = new LogDgt__c(
            LogDate__c = result.ResultDate == null ? AqEnv.now() : result.ResultDate,
            Level__c = result.Level,
            Severity__c = result.Severity,
            Code__c = result.Code,
            Source__c = result.Source,
            ResultType__c = result.Type,
            ScopeType__c = result.ScopeType,
            Scope__c = result.Scope,
            Message__c = result.Message
        );

        if (result.Detail != null) {
            if (result.Detail instanceof String) {
                log.Detail__c = (String)result.Detail;
            } else {
                log.Detail__c = JSON.serialize(result.Detail);
            }
        } else {
            log.Detail__c = JSON.serialize(result);
        }

        return log;
    }

    /**
     * @description Write the result to a log record
     */
    public static LogDgt__c logResult(AqResult result) {

        LogDgt__c log = generateLogRecord(result);
        // Method creates log records for the application. 
        // Log records should be created in system context, so CRUD/FLS enforcement omitted
        AqDml.insecureInsert(log);
        return log;
    }

    /**
     * @description Convenience, convert exception to result and log
     */
    public static LogDgt__c logException(System.Exception e, String source) {
        return logResult(
            new AqResultBuilder()
                .setException(e)
                .setSource(source)
                .createAqResult()
        );
    }

    /**
     * @description Convenience, convert exception to result and log
     */
    public static LogDgt__c logException(System.Exception e, String source, String scopeType, String scope) {
        return logResult(
            new AqResultBuilder()
                .setException(e)
                .setSource(source)
                .setScopeType(scopeType)
                .setScope(scope)
                .createAqResult()
        );
    }

    /**
     * @description Retrieve a log by ID
     */
    public static LogDgt__c retrieve(Id logId) {
        AqSoql query = new AqSoql(LOG_SOBJECT_TYPE)
            .withColumns(LOG_FIELDS)
            .withWhere('Id = :logId');
        
        return (LogDgt__c) Aq.exactlyOne(
            LogDgt__c.SObjectType, 
            (List<LogDgt__c>) Database.query(query.getQueryString())
        );

    }

    /**
     * @description Return most recent log entry, most useful for testing
     */
    public static LogDgt__c getMostRecent() {

        AqSoql query = new AqSoql(LOG_SOBJECT_TYPE)
            .withColumns(LOG_FIELDS)
            .withOrderBy(new List<String>{'Name DESC'})
            .withRowLimit(1);

        List<LogDgt__c> logs = (List<LogDgt__c>) Database.query(query.getQueryString());

        if (logs.isEmpty()) {
            return null;
        } else {
            return logs[0];
        }
    }

}