force-app/AqLib/apex/core/main/objects/LogDgt__c/LogDgt__c.object-meta.xml
<CustomObject>
    <description>Event logging object.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Unique programmatic identifier for the event, use for filtering, workflows, etc.</description>
    <inlineHelpText>Unique programmatic identifier for the event, use for filtering, workflows, etc.</inlineHelpText>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/Detail__c.field-meta.xml
<CustomField>
    <fullName>Detail__c</fullName>
    <description>Detail such as stack trace, should be in JSON format whenever possible.</description>
    <inlineHelpText>Detail such as stack trace, should be in JSON format whenever possible.</inlineHelpText>
    <label>Detail</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Specifies whether the event is directed to the end user, indicates a business rule violation, or indicates an internal error. Used to determine the amount of detail shown to the end user.</description>
    <inlineHelpText>Specifies whether the event is directed to the end user, indicates a business rule violation, or indicates an internal error. Used to determine the amount of detail shown to the end user.</inlineHelpText>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/LogDate__c.field-meta.xml
<CustomField>
    <fullName>LogDate__c</fullName>
    <defaultValue>Now()</defaultValue>
    <description>Date and time of the event.</description>
    <inlineHelpText>Date and time of the event.</inlineHelpText>
    <label>Log Date</label>
    <type>DateTime</type>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The main text message associated with the event.</description>
    <inlineHelpText>The main text message associated with the event.</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/ResultType__c.field-meta.xml
<CustomField>
    <fullName>ResultType__c</fullName>
    <description>When the event indicates successful result of an operation, this indicates the data type of the result.</description>
    <inlineHelpText>When the event indicates successful result of an operation, this indicates the data type of the result.</inlineHelpText>
    <label>Result Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>Use to indicate the area that the event refers to, such as the related field or fields or the JSON path.</description>
    <inlineHelpText>Use to indicate the area that the event refers to, such as the related field or fields or the JSON path.</inlineHelpText>
    <label>Scope</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/ScopeType__c.field-meta.xml
<CustomField>
    <fullName>ScopeType__c</fullName>
    <description>The type of object that the scope refers to.</description>
    <inlineHelpText>The type of object that the scope refers to.</inlineHelpText>
    <label>Scope Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>Indicates whether the event represents an error, warning, or is informational.</description>
    <inlineHelpText>Indicates whether the event represents an error, warning, or is informational.</inlineHelpText>
    <label>Severity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>PartialError</fullName>
                <label>Partial Error</label>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>RolledBack</fullName>
                <label>Rolled Back</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/AqLib/apex/core/main/objects/LogDgt__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Indicates the class, function, page, or other component where the event originated.</description>
    <inlineHelpText>Indicates the class, function, page, or other component where the event originated.</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/TestObject__c.object-meta.xml
<CustomObject>
    <description>This object exists only to provide test coverage for common trigger methods. It should only be populated in tests and never contain data in production.</description>
    <label>Test Object</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/Checkbox__c.field-meta.xml
<CustomField>
    <fullName>Checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Test Checkbox field.</description>
    <label>Checkbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Test Currency field</description>
    <label>Currency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Test Date field.</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/DateTime__c.field-meta.xml
<CustomField>
    <fullName>DateTime__c</fullName>
    <description>Test DateTime field.</description>
    <label>DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Test Email field.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/Integer__c.field-meta.xml
<CustomField>
    <fullName>Integer__c</fullName>
    <description>Test integer field.</description>
    <label>Integer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/LongText__c.field-meta.xml
<CustomField>
    <fullName>LongText__c</fullName>
    <description>Test Long Text field.</description>
    <label>Long Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/MultiPicklist__c.field-meta.xml
<CustomField>
    <fullName>MultiPicklist__c</fullName>
    <description>Test multi-select picklist.</description>
    <label>Multi Picklist</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value One</fullName>
            </value>
            <value>
                <fullName>Value Two</fullName>
            </value>
            <value>
                <fullName>Value Three</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <description>Test Percent field.</description>
    <label>Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Test Phone field.</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <description>Test Picklist field.</description>
    <label>Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value One</fullName>
            </value>
            <value>
                <fullName>Value Two</fullName>
            </value>
            <value>
                <fullName>Value Three</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/RequiredText__c.field-meta.xml
<CustomField>
    <fullName>RequiredText__c</fullName>
    <description>Text field that&#39;s required.</description>
    <inlineHelpText>Text field that&#39;s required.</inlineHelpText>
    <label>Required Text</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/RichText__c.field-meta.xml
<CustomField>
    <fullName>RichText__c</fullName>
    <description>Test RichText field.</description>
    <label>RichText</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <description>Test Text field.</description>
    <label>Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/TextArea__c.field-meta.xml
<CustomField>
    <fullName>TextArea__c</fullName>
    <description>Text TextArea field.</description>
    <label>TextArea</label>
    <type>TextArea</type>
</CustomField>

force-app/AqLib/apex/core/tests/objects/TestObject__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <description>Test URL field.</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/AqLib/apex/core/tests/classes/AqTest.cls
/*
 * Copyright (c) 2022, Aquiva Labs LLC. All rights reserved.
 * 
 * 
 * Redistribution and use in source and binary forms, with or without modification, 
 *   are permitted provided that the following conditions are met:
 * 
 * - Redistributions of source code must retain the above copyright notice, 
 *     this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice, 
 *     this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 * - Neither the name of the Aquiva Labs LLC nor the names of its contributors
 *     may be used to endorse or promote products derived from this software without
 *     specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
 *  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL 
 *  THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 *  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**/

/**
 * @description Helpers for testing
 * @group apex/core
**/
@isTest
public inherited sharing class AqTest {

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //Addional asserts

    //Assert that a list of strings is equivalent to expected multi-select picklist colon-separated string
    public static void assertMultiSelectPicklistEquals(String expected, List<String> actual) {

        String actualString = actual == null ? '' : String.join(actual, ';');
        System.assertEquals(expected, actualString);
    }

    //Assert that a colon-separate string value is equal to corresponding list of strings
    public static void assertMultiSelectPicklistEquals(List<String> expected, String actual) {

        String expectedString = expected == null ? '' : String.join(expected, ';');
        System.assertEquals(expectedString, actual);
    }


    //Same as System.assertEquals except consider null == false
    public static void assertBooleanEquals(Boolean expected, Boolean actual) {

        Boolean expectedNotNull = expected == null ? false : expected;
        Boolean actualNotNull = actual == null ? false : actual;
        System.assertEquals(expectedNotNull, actualNotNull);
    }

    //Assure no LogDgt__c with Error severity was inserted
    public static void assertNoErrorLogs() {

        List<LogDgt__c> errorLogs = [
            SELECT Id, LogDate__c, Level__c, Severity__c, Code__c, Source__c, ResultType__c, ScopeType__c, Scope__c, Message__c, Detail__c
            FROM LogDgt__c WHERE Severity__c IN :AqResult.SEVERITIES_ERROR];

        if (!errorLogs.isEmpty()) {
            System.assert(false, JSON.serializePretty(errorLogs));
        }
    }

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //AqResult helpers

    public static void assertSuccess(AqResult result) {
        //Null is always considered successful result
        if (result == null) {
            System.assert(true);
        } else {
            System.assertEquals(true, result.Severity == AqResult.SEVERITY_SUCCESS, result);
        }
    }

    public static void assertAborted(AqResult result) {
        System.assertEquals(AqResult.SEVERITY_ABORTED, result.Severity, result);
    }

    public static void assertError(AqResult result) {
        System.assertEquals(AqResult.SEVERITY_ERROR, result.Severity, result);
    }

    public static void assertError(Type resultType, AqResult result) {
        assertError(result);
        System.assertEquals(resultType.getName(), result.Type, result);
    }

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //Database result helpers

    public static void assertSuccess(Database.SaveResult saveResult) {
        System.assertEquals(true, saveResult.isSuccess(), saveResult);
    }

    //Assert database save result has expected error code.
    public static void assertDatabaseError(Database.SaveResult saveResult, String expectedStatusCode) {
        System.assert(saveResult != null, 'Null SaveResult');
        System.assertEquals(false, saveResult.isSuccess(), 'SaveResult is success.');
        System.assertEquals(expectedStatusCode, String.valueOf(saveResult.getErrors()[0].getStatusCode()));
    }

    //Assert database save result has FIELD_CUSTOM_VALIDATION_EXCEPTION error code.
    public static void assertCustomValidationError(Database.SaveResult saveResult) {
        assertDatabaseError(saveResult, 'FIELD_CUSTOM_VALIDATION_EXCEPTION');
    }

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //Visualforce helpers

    //Convenience for setting a query parameter for the current page
    public static void setQueryParameter(String name, String value) {
        ApexPages.currentPage().getParameters().put(name, value);
    }

    //Assert page currently has no messages
    public static void assertNoPageMessages() {
        System.assert(!ApexPages.hasMessages(), 'Unexpected page messages were found: ' + ApexPages.getMessages());
    }

    //Assert page currently has no messages
    public static void assertNoPageErrors() {
        System.assert(!
            ApexPages.hasMessages(ApexPages.Severity.ERROR) && !ApexPages.hasMessages(ApexPages.Severity.FATAL),
            'Unexpected error messages were found: ' + ApexPages.getMessages()
        );
    }

    //Assert page currently has confirmation message
    public static void assertConfirmMessage() {
        System.assert(
            ApexPages.hasMessages(ApexPages.Severity.CONFIRM),
            'Expected CONFIRM message not found: ' + ApexPages.getMessages()
        );
    }

    //Assert page currently has warning message
    public static void assertWarningMessage() {
        System.assert(
            ApexPages.hasMessages(ApexPages.Severity.WARNING),
            'Expected WARNING message not found: ' + ApexPages.getMessages()
        );
    }

    //Assert page currently has error message
    public static void assertErrorMessage() {
        System.assert(
            ApexPages.hasMessages(ApexPages.Severity.ERROR),
            'Expected ERROR message not found: ' + ApexPages.getMessages()
        );
    }

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //Email helpers

    //Asserts that email with subject like the expectedSubjectLike pattern was sent to all the expectedWhoIds
    //This only works for emails for contacts or leads that are added as activities.
    public static void assertEmailsSent(String expectedSubjectLike, Set<ID> expectedWhoIds) {
        assertEmailsSent(true, expectedSubjectLike, expectedWhoIds);
    }

    //Asserts that email with subject like the expectedSubjectLike pattern was NOT sent to all the expectedWhoIds
    //This only works for emails for contacts or leads that are added as activities.
    public static void assertEmailsNotSent(String expectedSubjectLike, Set<ID> expectedWhoIds) {
        assertEmailsSent(false, expectedSubjectLike, expectedWhoIds);
    }

    private static void assertEmailsSent(Boolean isExpected, String expectedSubjectLike, Set<ID> expectedWhoIds) {

        System.assert(expectedWhoIds != null && !expectedWhoIds.isEmpty(), 'expectedWhoIds must not be null or empty.');

        List<EmailMessageRelation> relations = [
            SELECT Id, RelationId
            FROM EmailMessageRelation
            WHERE EmailMessage.Subject LIKE :expectedSubjectLike
                AND RelationId IN :expectedWhoIds
                AND RelationType = 'ToAddress'
        ];

        Set<Id> actualWhoIds = Aq.getIdSet(relations, EmailMessageRelation.RelationId);
        for (Id expectedWhoId : expectedWhoIds) {
            if (isExpected == true && !actualWhoIds.contains(expectedWhoId)) {
                System.assert(false, AqString.format('No {0} email found for who ID {1}', expectedSubjectLike, expectedWhoId));
                return;
            } else if (isExpected != true && actualWhoIds.contains(expectedWhoId)) {
                System.assert(false, AqString.format('Unexpected {0} email found for who ID {1}', expectedSubjectLike, expectedWhoId));
                return;
            }
        }
    }

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //Misc helpers

    //Return a valid picklist value from the specific picklist field
    public static String getPicklistValue(SObjectField field, Integer index) {
        return field.getDescribe().getPicklistValues()[index].getValue();
    }

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //Test object

    //Return test record will all values populated, not inserted
    public static TestObject__c getFullTestRecord() {

        TestObject__c testRecord = new TestObject__c(
            RecordTypeId = Aq.getRecordTypeId(TestObject__c.SObjectType, AqObjAqTestObject.RECORD_TYPE_1),
            Name = 'Test1',
            Checkbox__c = true,
            Currency__c = 9.99,
            Date__c = Date.newInstance(2017, 5, 9),
            DateTime__c = Datetime.newInstance(2017, 5, 9, 12, 0, 0),
            Email__c = 'test@testy.com',
            Integer__c = 123,
            LongText__c = 'Long text value\r\n'.repeat(100),
            MultiPicklist__c = 'Value One;Value Two',
            Percent__c = 66.5,
            Phone__c = '603-555-1212',
            Picklist__c = 'Value One',
            RequiredText__c = 'Required text value',
            RichText__c = 'Rich text value',
            Text__c = 'Text value',
            TextArea__c = 'Text area value',
            Url__c = 'https://www.aquivalabs.com'
        );

        return testRecord;
    }

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //Run As

    public static final User adminUser = new User (Id = UserInfo.getUserId());

    public static void setup() {
        insert new PermissionSetAssignment (
                AssigneeId = adminUser.Id,
                PermissionSetId = [SELECT Id FROM PermissionSet WHERE Name = 'AqLibAdmin' LIMIT 1].Id
        );
    }

}