force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UTXO_Address__c/UTXO_Address__c.object-meta.xml
<CustomObject>
    <label>UTXO Address</label>
    <nameField>
        <displayFormat>UTXO-{0000}</displayFormat>
        <label>UTXO Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UTXO Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UTXO_Address__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UTXO_Address__c/fields/Wallet__c.field-meta.xml
<CustomField>
    <fullName>Wallet__c</fullName>
    <label>Wallet</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>UTXO Addresses</relationshipLabel>
    <relationshipName>UTXO_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UTXO_Asset__c/UTXO_Asset__c.object-meta.xml
<CustomObject>
    <label>UTXO Asset</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>UTXO Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UTXO Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/UTXO_Asset__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <type>Number</type>
    <precision>18</precision>
    <scale>6</scale>
</CustomField> 

force-app/main/default/objects/UTXO_Asset__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>UTXO Assets</relationshipLabel>
    <relationshipName>UTXO_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UTXO_Asset__c/fields/Decimals__c.field-meta.xml
<CustomField>
    <fullName>Decimals__c</fullName>
    <label>Decimals</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField> 

force-app/main/default/objects/UTXO_Asset__c/fields/Fingerprint__c.field-meta.xml
<CustomField>
    <fullName>Fingerprint__c</fullName>
    <label>Fingerprint</label>
    <length>255</length>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/UTXO_Asset__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/UTXO_Asset__c/fields/Policy_ID__c.field-meta.xml
<CustomField>
    <fullName>Policy_ID__c</fullName>
    <label>Policy ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/UTXO_Asset__c/fields/UTXO_Address__c.field-meta.xml
<CustomField>
    <fullName>UTXO_Address__c</fullName>
    <label>UTXO Address</label>
    <referenceTo>UTXO_Address__c</referenceTo>
    <relationshipLabel>UTXO Assets</relationshipLabel>
    <relationshipName>UTXO_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/selectors/UTXOAssetSelector.cls
public with sharing class UTXOAssetSelector {
    public static List<UTXO_Asset__c> getAssetsByWalletId(String walletId) {
        return [
            SELECT Id, UTXO_Address__c, Asset__c, Amount__c, Name__c, 
                    Decimals__c, Policy_ID__c, Fingerprint__c,
                    UTXO_Address__r.Address__c, UTXO_Address__r.Index__c
            FROM UTXO_Asset__c
            WHERE UTXO_Address__r.Wallet__c = :walletId
            WITH SECURITY_ENFORCED
            ORDER BY UTXO_Address__r.Index__c, Asset__c
        ];
    }
} 