force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outbound_Transaction__c/Outbound_Transaction__c.object-meta.xml
<CustomObject>
    <label>Outbound Transaction</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Outbound Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Outbound_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <type>Number</type>
    <precision>16</precision>
    <scale>6</scale>
</CustomField>

force-app/main/default/objects/Outbound_Transaction_Line__c/Outbound_Transaction_Line__c.object-meta.xml
<CustomObject>
    <label>Outbound Transaction Line</label>
    <nameField>
        <displayFormat>OTL-{0000}</displayFormat>
        <label>Outbound Transaction Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject> 

force-app/main/default/objects/Outbound_Transaction_Line__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField> 

force-app/main/default/objects/Outbound_Transaction_Line__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/Outbound_Transaction_Line__c/fields/Outbound_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Transaction__c</fullName>
    <label>Outbound Transaction</label>
    <referenceTo>Outbound_Transaction__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>Outbound_Transaction_Lines</relationshipName>
    <type>MasterDetail</type>
</CustomField> 

force-app/main/default/classes/selectors/OutboundTransactionLineSelector.cls
public with sharing class OutboundTransactionLineSelector {
    public static List<Outbound_Transaction_Line__c> getTransactionLinesByOutboundId(Id outboundTransactionId) {
        return [
            SELECT Id, Amount__c, Asset__c
            FROM Outbound_Transaction_Line__c
            WHERE Outbound_Transaction__c = :outboundTransactionId
            WITH SECURITY_ENFORCED
            ORDER BY Id
        ];
    }
} 