force-app/main/default/objects/AdaSettings__c/AdaSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AdaSettings</label>
</CustomObject>

force-app/main/default/objects/AdaSettings__c/fields/BlockfrostProjectId__c.field-meta.xml
<CustomField>
    <fullName>BlockfrostProjectId__c</fullName>
    <description>The Blockfrost Project ID for Cardano API integration.</description>
    <label>Blockfrost Project ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdaSettings__c/fields/Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Private_Key__c</fullName>
    <label>Private Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdaWalletsService.cls
public with sharing class AdaWalletsService {
    private static AdaSettings__c adaSettings;

    private static AdaSettings__c getSettings() {
        if (adaSettings == null) {
            adaSettings = AdaSettings__c.getOrgDefaults();
        }
        return adaSettings;
    }

    public static String getPrivateKey() {
        AdaSettings__c adaSettings = getSettings();
        return adaSettings.Private_Key__c != null ? adaSettings.Private_Key__c : '';
    }

    public static String getBlockfrostProjectId() {
        AdaSettings__c adaSettings = getSettings();
        return adaSettings.BlockfrostProjectId__c != null ? adaSettings.BlockfrostProjectId__c : '';
    }

    public static void setPrivateKey(String key) {
        AdaSettings__c adaSettings = getSettings();
        adaSettings.Private_Key__c = key;
        upsert adaSettings;
    }

    public static void setBlockfrostProjectId(String blockfrostProjectId) {
        AdaSettings__c adaSettings = getSettings();
        adaSettings.BlockfrostProjectId__c = blockfrostProjectId;
        upsert adaSettings;
    }
}