force-app/logger/sfdc-logger/objects/Log_Ada__c/fields/Logged_at__c.field-meta.xml
<CustomField>
    <fullName>Logged_at__c</fullName>
    <description>Time of the event happened</description>
    <label>Logged at</label>
    <type>DateTime</type>
</CustomField>

force-app/logger/sfdc-logger/objects/Log_Ada__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Log Details</description>
    <label>Message</label>
    <length>131070</length>
    <type>LongTextArea</type>
</CustomField>

force-app/logger/sfdc-logger/objects/Log_Ada__c/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <description>User which triggered the Log</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AdaLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/logger/sfdc-logger/objects/Log_Ada__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>Severity of the event happened</description>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/logger/sfdc-logger/objects/Logger_Config_Ada__c/Logger_Config_Ada__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Logger Configuration Settings</description>
    <label>Logger Config</label>
</CustomObject>

force-app/logger/sfdc-logger/objects/Logger_Config_Ada__c/fields/Is_Debug_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Debug_Enabled__c</fullName>
    <description>Identifies if the Logs of Severety Debug should be created</description>
    <defaultValue>false</defaultValue>
    <label>Is Debug Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/logger/sfdc-logger/objects/Logger_Config_Ada__c/fields/Is_Error_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Error_Enabled__c</fullName>
    <description>Identifies if the Logs of Severety Error should be created</description>
    <defaultValue>false</defaultValue>
    <label>Is Error Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/logger/sfdc-logger/objects/Logger_Config_Ada__c/fields/Is_Success_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Success_Enabled__c</fullName>
    <description>Identifies if the Logs of Severety Success should be created</description>
    <defaultValue>false</defaultValue>
    <label>Is Success Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/logger/sfdc-logger/classes/LoggerAda.cls
public with sharing class LoggerAda {
    private static final Logger_Config_Ada__c LOGGER_CONFIG = Logger_Config_Ada__c.getInstance();
    private static List<Log_Ada__c> logs = new List<Log_Ada__c>();

    public static void log(LoggerAda.LogSeverity severity, String message) {
        if (severity != null && isEnabled(severity)) {
            Log_Ada__c log = new Log_Ada__c();
            log.Severity__c = severity.name();
            log.Message__c = message;
            log.Running_User__c = UserInfo.getUserId();
            log.Logged_at__c = DateTime.now();
            logs.add(log);
        }
    }

    public static void logDebug(String message) {
        log(LoggerAda.LogSeverity.DEBUG, message);
    }

    public static void logInfo(String message) {
        log(LoggerAda.LogSeverity.INFO, message);
    }

    public static void logSuccess(String message) {
        log(LoggerAda.LogSeverity.SUCCESS, message);
    }

    public static void logError(String message) {
        log(LoggerAda.LogSeverity.ERROR, message);
    }

    public static void logError(Exception e) {
        log(LoggerAda.LogSeverity.ERROR, e.getTypeName() + ': ' + e.getMessage() + '\n\n' + e.getStackTraceString());
    }

    public static void commitLogs() {
        if (!logs.isEmpty()) {
            // System mode as logs should be inserted nevertheless of permissions that user has
            insert as system logs;
            logs.clear();
        }
    }

    private static Boolean isEnabled(LoggerAda.LogSeverity severity) {
        Boolean isEnabled = false;
        if (LOGGER_CONFIG.Is_Logger_Enabled__c) {
            switch on severity {
                when DEBUG {
                    isEnabled = LOGGER_CONFIG.Is_Debug_Enabled__c;
                }
                when INFO {
                    isEnabled = LOGGER_CONFIG.Is_Info_Enabled__c;
                }
                when SUCCESS {
                    isEnabled = LOGGER_CONFIG.Is_Success_Enabled__c;
                }
                when ERROR {
                    isEnabled = LOGGER_CONFIG.Is_Error_Enabled__c;
                }
            }
        }

        return isEnabled;
    }

    public enum LogSeverity {
        DEBUG,
        INFO,
        SUCCESS,
        ERROR
    }
}