force-app/main/default/objects/Inbound_Transaction__c/Inbound_Transaction__c.object-meta.xml
<CustomObject>
    <label>Inbound Transaction</label>
    <nameField>
        <label>Inbound Transaction Name</label>
        <type>AutoNumber</type>
        <displayFormat>IT-{0000}</displayFormat>
    </nameField>
    <pluralLabel>Inbound Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Wallet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wallet</label>
        <referenceTo>Wallet__c</referenceTo>
        <relationshipLabel>Inbound Transactions</relationshipLabel>
        <relationshipName>Inbound_Transactions</relationshipName>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Inbound_Transaction__c/fields/Block_Height__c.field-meta.xml
<CustomField>
    <fullName>Block_Height__c</fullName>
    <label>Block Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField> 

force-app/main/default/objects/Inbound_Transaction__c/fields/Block_Time__c.field-meta.xml
<CustomField>
    <fullName>Block_Time__c</fullName>
    <label>Block Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField> 

force-app/main/default/objects/Inbound_Transaction__c/fields/Transaction_Hash__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Hash__c</fullName>
    <externalId>true</externalId>
    <label>Transaction Hash</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Transaction__c/fields/Transaction_Index__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Index__c</fullName>
    <label>Transaction Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField> 

force-app/main/default/objects/Inbound_Transaction__c/fields/UTXO_Address__c.field-meta.xml
<CustomField>
    <fullName>UTXO_Address__c</fullName>
    <label>UTXO Address</label>
    <type>MasterDetail</type>
    <referenceTo>UTXO_Address__c</referenceTo>
    <relationshipLabel>Inbound Transactions</relationshipLabel>
    <relationshipName>Inbound_Transactions</relationshipName>
    <reparentableMasterDetail>true</reparentableMasterDetail>
</CustomField> 

force-app/main/default/objects/Inbound_Transaction__c/fields/Wallet__c.field-meta.xml
<CustomField>
    <fullName>Wallet__c</fullName>
    <label>Wallet</label>
    <type>Lookup</type>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>Inbound Transactions</relationshipLabel>
    <relationshipName>Inbound_Transactions</relationshipName>
</CustomField> 

force-app/main/default/objects/UTXO_Address__c/UTXO_Address__c.object-meta.xml
<CustomObject>
    <label>UTXO Address</label>
    <nameField>
        <displayFormat>UTXO-{0000}</displayFormat>
        <label>UTXO Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UTXO Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UTXO_Address__c/fields/Wallet__c.field-meta.xml
<CustomField>
    <fullName>Wallet__c</fullName>
    <label>Wallet</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>UTXO Addresses</relationshipLabel>
    <relationshipName>UTXO_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/selectors/InboundTransactionSelector.cls
public with sharing class InboundTransactionSelector {
    public static List<Inbound_Transaction__c> getInboundTransactionsByUtxoAddressId(Id utxoAddressId) {
        return [
            SELECT Id, Transaction_Hash__c, Block_Height__c, Block_Time__c, Transaction_Index__c
            FROM Inbound_Transaction__c
            WHERE UTXO_Address__c = :utxoAddressId
            WITH SECURITY_ENFORCED
        ];
    }

    public static List<Inbound_Transaction__c> getInboundTransactionsByWalletId(Id walletId) {
        return [
            SELECT Id, Name, Transaction_Hash__c, CreatedDate, UTXO_Address__c
            FROM Inbound_Transaction__c
            WHERE UTXO_Address__r.Wallet__c = :walletId
            WITH SECURITY_ENFORCED
            ORDER BY CreatedDate DESC
        ];
    }
} 