force-app/main/default/objects/Wallet_Set__c/Wallet_Set__c.object-meta.xml
<CustomObject>
    <label>Wallet Set</label>
    <nameField>
        <displayFormat>WS-{0000}</displayFormat>
        <label>Wallet Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wallet Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wallet_Set__c/fields/Seed_Phrase__c.field-meta.xml
<CustomField>
    <fullName>Seed_Phrase__c</fullName>
    <description>The Seed Phrase to Generate Wallets</description>
    <label>Seed Phrase</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Wallet_Set__c/fields/Wallet_Name__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Name__c</fullName>
    <label>Wallet Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WalletSetSelector.cls
public with sharing class WalletSetSelector {
    public static Wallet_Set__c getWalletSetById(Id walletSetId) {
        return [SELECT Id, Name, Wallet_Name__c FROM Wallet_Set__c WHERE Id = :walletSetId LIMIT 1];
    }
    
    public static Wallet_Set__c getWalletSetWithSeedPhrase(Id walletSetId) {
        return [SELECT Id, Wallet_Name__c, Seed_Phrase__c FROM Wallet_Set__c WHERE Id = :walletSetId WITH SECURITY_ENFORCED LIMIT 1];
    }
}