force-app/main/default/objects/Wallet_Set__c/Wallet_Set__c.object-meta.xml
<CustomObject>
    <label>Wallet Set</label>
    <nameField>
        <displayFormat>WS-{0000}</displayFormat>
        <label>Wallet Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wallet Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wallet_Set__c/fields/Seed_Phrase__c.field-meta.xml
<CustomField>
    <fullName>Seed_Phrase__c</fullName>
    <description>The Seed Phrase to Generate Wallets</description>
    <label>Seed Phrase</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/EncryptedDataService.cls
public with sharing class EncryptedDataService {
    public static String getEncryptedSeedPhrase(Id recordId) {
        Wallet_Set__c walletSet = WalletSetSelector.getWalletSetWithSeedPhrase(recordId);

        if (!hasAccessToDecrypt()) {
            throw new SecurityException('Access denied to decrypt seed phrase');
        }

        return walletSet.Seed_Phrase__c;
    }

    public static Boolean hasAccessToDecrypt() {        
        try {
            if (!Schema.sObjectType.PermissionSetAssignment.isAccessible() || 
                !Schema.sObjectType.PermissionSet.isAccessible()) {
                return false;
            }
            
            Set<Id> psIds = new Set<Id>();
            for (PermissionSetAssignment psa : [SELECT PermissionSetId FROM PermissionSetAssignment WHERE AssigneeId = :UserInfo.getUserId()]) {
                psIds.add(psa.PermissionSetId);
            }
            
            Id requiredPsId = [SELECT Id FROM PermissionSet WHERE Name = 'Ada_Wallet_Seed_Phrase' LIMIT 1].Id;
            
            Boolean hasAccess = requiredPsId != null && psIds.contains(requiredPsId);
            
            return hasAccess;
        } catch (Exception e) {
            return false;
        }
    }
}