force-app/main/default/objects/Wallet_Set__c/Wallet_Set__c.object-meta.xml
<CustomObject>
    <label>Wallet Set</label>
    <nameField>
        <displayFormat>WS-{0000}</displayFormat>
        <label>Wallet Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wallet Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wallet_Set__c/fields/Seed_Phrase__c.field-meta.xml
<CustomField>
    <fullName>Seed_Phrase__c</fullName>
    <description>The Seed Phrase to Generate Wallets</description>
    <label>Seed Phrase</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Wallet_Set__c/fields/Wallet_Name__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Name__c</fullName>
    <label>Wallet Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/controllers/WalletSetCtrl.cls
public with sharing class WalletSetCtrl {
    @AuraEnabled
    public static Id createWalletSet(String walletName, String seedPhrase) {
        try {
            Wallet_Set__c walletSet = new Wallet_Set__c();
            walletSet.Wallet_Name__c = walletName;
            walletSet.Seed_Phrase__c = DataEncryptor.encryptHmac(seedPhrase);
            insert walletSet;
            Logger.logInfo('Wallet Set was created by ' + UserInfo.getName() + ' (Id: ' + UserInfo.getUserId() + ') with ID: ' + walletSet.Id);
            return walletSet.Id;
        } catch (Exception e) {
            throw new AuraHandledException('Error creating Wallet Set: ' + e.getMessage());
        } finally {
            Logger.commitLogs();
        }
    }
}