force-app/logger/sfdc-logger/objects/Logger_Config_Ada__c/Logger_Config_Ada__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Logger Configuration Settings</description>
    <label>Logger Config</label>
</CustomObject>

force-app/logger/sfdc-logger/objects/Logger_Config_Ada__c/fields/Is_Debug_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Debug_Enabled__c</fullName>
    <description>Identifies if the Logs of Severety Debug should be created</description>
    <defaultValue>false</defaultValue>
    <label>Is Debug Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/logger/sfdc-logger/objects/Logger_Config_Ada__c/fields/Is_Error_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Error_Enabled__c</fullName>
    <description>Identifies if the Logs of Severety Error should be created</description>
    <defaultValue>false</defaultValue>
    <label>Is Error Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/logger/sfdc-logger/objects/Logger_Config_Ada__c/fields/Is_Success_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Success_Enabled__c</fullName>
    <description>Identifies if the Logs of Severety Success should be created</description>
    <defaultValue>false</defaultValue>
    <label>Is Success Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LoggerServiceADA.cls
public without sharing class LoggerServiceADA {
    private Logger_Config_Ada__c loggerSettings;

    public LoggerServiceADA() {
        loggerSettings = Logger_Config_Ada__c.getOrgDefaults();
    }

    public Logger_Config_Ada__c getConfig() {
        return loggerSettings;
    }

    public void updateLoggerService(Boolean enabled) {
        loggerSettings.Is_Debug_Enabled__c = enabled;
        loggerSettings.Is_Error_Enabled__c = enabled;
        loggerSettings.Is_Info_Enabled__c = enabled;
        loggerSettings.Is_Logger_Enabled__c = enabled;
        loggerSettings.Is_Success_Enabled__c = enabled;

        upsert as system loggerSettings;
    }

    public Boolean isLoggingEnabled() {
        return loggerSettings.Is_Logger_Enabled__c;
    }
}